### ISSUE TITLE
Feature: Multiple tags and tags removal

### ISSUE THREAD

**Issue by amanbolat** [RainingClouds/easytags#2]
**Idea**
I have some features that can be added to this library.
I found that some times I need add multiple tags and remove them if I don't want them anymore. 

**How it should work**
`//go:generate easytags $GOFILE "json,xml,sql"`
will add three tags: json,xml,sql

`//go:generate easytags $GOFILE "json,xml"`
will add two tags:  json,xml and will remove any other tags, if they exist.

**Implementation**

Add new function to create new tag value every time
```go
func parseTags(field *ast.Field, tags []string) string {
	var tagValues []string
	fieldName := field.Names[0].String()

	for _, tag := range tags {
		var value string
		if strings.Contains(field.Tag.Value, fmt.Sprintf("%s:\"-\"", tag)) {
			value = "-"
		} else {
			value = ToSnake(fieldName)
		}

		tagValues = append(tagValues, fmt.Sprintf("%s:\"%s\"", tag, value))
	}

	if len(tagValues) == 0 {
		return ""
	}

	newValue := "`" + strings.Join(tagValues, " ") + "`"

	return newValue
}
```

Every time process tags and change value to new one
```go
func processTags(x *ast.StructType, tagNames []string) {
	for _, field := range x.Fields.List {
		if len(field.Names) == 0 {
			continue
		}

		newTags := parseTags(field, tagNames)

		field.Tag = &ast.BasicLit{}
		field.Tag.ValuePos = field.Type.Pos() + 1
		field.Tag.Kind = token.STRING
		field.Tag.Value = newTags
	}
}
```

If you accept this idea, I can create pull request.

**Comment by aniketawati** [comment]
Looks good to me. Please send a PR.
