### ISSUE TITLE
Ability to ignore fields that contain a certain prefix

### ISSUE THREAD

**Issue by FM1337** [RainingClouds/easytags#5]
Just a suggestion for a future version, maybe if possible, you could add the ability to ignore struct fields that start with a certain prefix

e.g easytags [-i <prefix>] <file> <tags>

easytags -i Get structs.go json

**Comment by aniketawati** [comment]
Do you mean keep the existing tag as is? If so that was supposed to be the default behavior. i.e. ignoring all existing tags. That bug was raised and fixed recently, PR #7
